name: app
description: A dating app actually designed to be deleted.

publish_to: 'none' # Remove this to publish to pub.dev

version: 0.1.6

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  flutter_chat_bubble: any
  intl: any
  flutter_svg: any
  http: ^1.2.1
  async: ^2.11.0
  image_picker: ^1.1.0
  intl_phone_field: ^3.2.0
  multi_dropdown: ^3.0.1
  firebase_core: 3.15.1
  firebase_auth: 5.6.2
  firebase_ui_auth: ^1.13.1
  cloud_firestore: 5.6.11
  firebase_storage: 12.4.9
  firebase_analytics: 11.5.2
  firebase_performance: 0.10.1+9
  firebase_crashlytics: 4.3.9
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#ffffff"